### ISSUE TITLE
DeckManager compatability with CardManager

### ISSUE THREAD

**Issue by jokla17** [wtrwinberg/Kateesa#3]
The CardManager cannot fetch a specific deck from the DeckManager. The DeckManager seems to store Decks in an arraylist, that requires an index to get a specific Deck. The CardManager class will provide functionality that only requires a UUID to search for a Deck, so would it be possible for you to either:
- Store Deck's in a HashMap with the UUID as Key's --> DeckManager.deckMap.get(UUID);
- Or provide your own method, that can return a Deck-Object from the list, provided a UUID --> DeckManager.getFromUUID(UUID)

**Comment by wtrwinberg** [comment]
To solve the issue, we will still utillize the deck list implemented earlier - however, each deck now contains a UUID, which can be gathered by calling .getId() within the Deck object.
